### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ktquez** [vue-a11y/vue-axe-next#1]
## v3
- [x] Enable highlighting of elements with errors on the page;
- [x] i18n;
- [x] Announce "views" changes to the screen reader;
- [x] New documentation;
- [x] Add focus trap in the popup;
